"""add is_deleted to projects

Revision ID: 22dad7b11cbe
Revises: c1fc7ff7d27a
Create Date: 2026-08-24 20:40:55.632800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dad7b11cbe'
down_revision: Union[str, Sequence[str], None] = 'c1fc7ff7d27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
