"""add_activities_logs

Revision ID: 2dd20626453b
Revises: 63f9595f0c4f
Create Date: 2026-08-21 23:16:42.502748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd20626453b'
down_revision: Union[str, Sequence[str], None] = '63f9595f0c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('activities_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'activities_type')
    # ### end Alembic commands ###
