"""remove activities_type

Revision ID: 97bb60cde171
Revises: 2dd20626453b
Create Date: 2026-08-23 17:16:07.270282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97bb60cde171'
down_revision: Union[str, Sequence[str], None] = '2dd20626453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'activities_type')
    op.drop_column('tasks', 'task_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('activity_logs', sa.Column('activities_type', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
