"""add actor_role to activity_logs

Revision ID: dd4a2545cbc0
Revises: 22dad7b11cbe
Create Date: 2026-08-28 10:41:36.647224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4a2545cbc0'
down_revision: Union[str, Sequence[str], None] = '22dad7b11cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('actor_role', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_activity_logs_actor_role'), 'activity_logs', ['actor_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_actor_role'), table_name='activity_logs')
    op.drop_column('activity_logs', 'actor_role')
    # ### end Alembic commands ###
